### ISSUE TITLE
Reprosyn does not work on Python < 3.10 (tapas requires >=3.9)

### ISSUE THREAD

**Issue by fhoussiau** [alan-turing-institute/reprosyn#52]
Here is the result from the command line (poetry 1.2.2, reprosyn environment):

```
Using python3.9 (3.9.14)
Type "help", "copyright", "credits" or "license" for more information.
>>> import reprosyn
>>> import reprosyn.dataset
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/fhoussiau/workspace/reprosyn/src/reprosyn/dataset.py", line 9, in <module>
    class Dataset:
  File "/Users/fhoussiau/workspace/reprosyn/src/reprosyn/dataset.py", line 40, in Dataset
    def read_dataset(dataset: pd.DataFrame | str) -> pd.DataFrame:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

The reason seems to be that the pipe for union has only been added in Python 3.10 (https://github.com/tiangolo/typer/issues/371#issuecomment-1073649190). A solution is to add ``__future__`.

**Comment by callummole** [comment]
I see you have already closed this. I think for interoperability it should be able to work on python >= 3.9. The type annotation isn't needed.
